import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Generates src/core/board/migrations.ts — the drizzle migration journal
// embedded as data, so a compiled `deck` binary can migrate a fresh board
// without the drizzle/ folder on disk (store.ts prefers the folder in dev,
// same disk-first rule as the embedded UI assets).

function millisFrom(name: string): number {
  return Date.UTC(
    Number(name.slice(0, 4)),
    Number(name.slice(4, 6)) - 1,
    Number(name.slice(6, 8)),
    Number(name.slice(8, 10)),
    Number(name.slice(10, 12)),
    Number(name.slice(12, 14)),
  );
}

const root = process.cwd();
const dir = join(root, 'drizzle');
if (!existsSync(dir)) {
  console.error('embed-migrations: drizzle/ not found');
  process.exit(1);
}

const journal = readdirSync(dir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && existsSync(join(dir, entry.name, 'migration.sql')))
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b))
  .map((name) => ({
    sql: readFileSync(join(dir, name, 'migration.sql'), 'utf8'),
    timestamp: millisFrom(name),
    name,
  }));

const banner =
  '// GENERATED by scripts/embed-migrations.ts — do not edit; gitignored.\n' +
  '// Typed by migrations.d.ts; regenerated whenever drizzle-kit generates.\n';
const out = join(root, 'src', 'core', 'board', 'migrations.ts');
writeFileSync(out, `${banner}export const migrationsJournal = ${JSON.stringify(journal)};\n`);
console.log(`embed-migrations: embedded ${journal.length} migration(s) → ${out}`);
