import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const uiDir = join(root, 'dist', 'ui');
const shell = join(root, 'public', 'index.html');

if (!existsSync(uiDir)) {
  console.error('embed-ui: dist/ui not found — run `bun run build:ui` first');
  process.exit(1);
}
if (!existsSync(shell)) {
  console.error('embed-ui: public/index.html not found');
  process.exit(1);
}

const assets: Record<string, string> = { '/': readFileSync(shell, 'utf8') };
for (const name of readdirSync(join(root, 'public'))) {
  if (name.endsWith('.svg')) assets[`/${name}`] = readFileSync(join(root, 'public', name), 'utf8');
}
for (const name of readdirSync(uiDir)) {
  assets[`/ui/${name}`] = readFileSync(join(uiDir, name), 'utf8');
}

const banner =
  '// GENERATED by scripts/embed-ui.ts — do not edit; gitignored.\n' +
  '// Typed by ui-assets.d.ts; absent on fresh clones until build:ui runs.\n';
const out = join(root, 'src', 'server', 'ui-assets.ts');
writeFileSync(out, `${banner}export const uiAssets: Record<string, string> = ${JSON.stringify(assets)};\n`);
console.log(`embed-ui: embedded ${Object.keys(assets).length} files (${(JSON.stringify(assets).length / 1024).toFixed(1)} kB) → ${out}`);
