import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Generates src/core/projects/skill-assets.ts: relative skill path →
// SKILL.md content, so the compiled binary carries the agent skill pack
// (deck setup installs it into detected hosts). Unlike ui-assets (a build
// artifact, gitignored), this file is COMMITTED: it is authored content
// that ships, and committing it keeps tests + runtime working on fresh
// clones before any build. Re-run after editing .agents/skills/deck-*/.

const root = process.cwd();
const skillsDir = join(root, '.agents', 'skills');

if (!existsSync(skillsDir)) {
  console.error('embed-skills: .agents/skills not found');
  process.exit(1);
}

const assets: Record<string, string> = {};
for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
  if (!entry.isDirectory() || !entry.name.startsWith('deck-')) continue;
  const file = join(skillsDir, entry.name, 'SKILL.md');
  if (!existsSync(file)) continue;
  assets[`${entry.name}/SKILL.md`] = readFileSync(file, 'utf8');
}
if (Object.keys(assets).length === 0) {
  console.error('embed-skills: no deck-* skills found under .agents/skills');
  process.exit(1);
}

const banner =
  '// GENERATED by scripts/embed-skills.ts — do not edit by hand.\n' +
  '// Regenerate with `bun run scripts/embed-skills.ts` after editing\n' +
  '// .agents/skills/deck-*/SKILL.md. Committed (authored content that ships).\n';
const out = join(root, 'src', 'core', 'projects', 'skill-assets.ts');
writeFileSync(out, `${banner}export const skillAssets: Record<string, string> = ${JSON.stringify(assets)};\n`);
console.log(
  `embed-skills: embedded ${Object.keys(assets).length} skills ` +
    `(${(JSON.stringify(assets).length / 1024).toFixed(1)} kB) → ${out}`,
);
