import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const skillsDir = join(root, 'src', 'skills');

if (!existsSync(skillsDir)) {
  console.error('embed-skills: src/skills not found — the tracked authored source is missing');
  process.exit(1);
}

const assets: Record<string, string> = {};
for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
  if (!entry.isDirectory() || !entry.name.startsWith('deck-')) continue;
  const file = join(skillsDir, entry.name, 'SKILL.md');
  if (!existsSync(file)) continue;
  assets[`${entry.name}/SKILL.md`] = readFileSync(file, 'utf8');
}
if (Object.keys(assets).length === 0) {
  console.error('embed-skills: no deck-* skills found under src/skills');
  process.exit(1);
}

const banner =
  '// GENERATED by scripts/embed-skills.ts — do not edit by hand.\n' +
  '// Regenerate with `bun run scripts/embed-skills.ts` after editing\n' +
  '// .agents/skills/deck-*/SKILL.md. Committed (authored content that ships).\n';
const out = join(root, 'src', 'core', 'projects', 'skill-assets.ts');
writeFileSync(out, `${banner}export const skillAssets: Record<string, string> = ${JSON.stringify(assets)};\n`);
console.log(
  `embed-skills: embedded ${Object.keys(assets).length} skills ` +
    `(${(JSON.stringify(assets).length / 1024).toFixed(1)} kB) → ${out}`,
);
